[env:stm32_canbus]
platform = ststm32
board = genericSTM32F103CB
board_build.mcu = stm32f103cbt6
framework = arduino
upload_protocol = stlink

upload_flags =
    -c
    adapter serial 37FF71064E57343642BA1643

build_flags =
    -DHAL_CAN_MODULE_ENABLED
    ; Set HSE based on physical crystal
    -DHSE_VALUE=16000000U
    -Wall
    -Wextra
    -Werror
    -fno-exceptions
    -I../console

lib_deps =
    https://github.com/PaulStoffregen/SerialFlash.git

lib_extra_dirs =
    ; Explicitly select only required libraries from the local monorepo
    ../../../av-libraries/